#! /bin/sh

sxhkd &
compton &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          2
bspc config window_gap            10

bspc config focus_follows_pointer true
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config pointer_action3 resize_side

bspc config focused_border_color "#FFFFFF"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#000000"
